---
# Installing system packages

- name: Installing system packages
  pacman:
    state: latest
    name:
      - archey3
      - curl
      - dnsutils
      - dosfstools
      - fzf
      - git
      - htop
      - httpie
      - iputils
      - mlocate
      - mono
      - ntfsprogs
      - ntp
      - openssh
      - openssl
      - p7zip
      - speedtest-cli
      - sudo
      - tar
      - tree
      - unrar
      - unzip
      - wget
      - which
      - whois
      - zip

- name: Installing system packages (AUR)
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - downgrade

- name: Starting NTP daemon at boot time
  command: systemctl enable ntpd

- name: Adding default user
  user: name={{username}} groups=wheel append=yes

- name: Creating 'programs' folder
  file: path="/home/{{username}}/programs" owner={{username}} group={{username}} state=directory

- name: Creating 'workspaces' folder
  file: path="/home/{{username}}/workspaces" owner={{username}} group={{username}} state=directory

- name: Adding 'wheel' group to sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) ALL'"

- name: Set en_US.UTF8 locale
  replace:
    dest: /etc/locale.gen
    regexp: "^#en_US.UTF-8 UTF-8"
    replace: "en_US.UTF-8 UTF-8"

- name: Generate locale
  command: locale-gen

- name: Configure pacman.conf
  replace:
    dest: /etc/pacman.conf
    regexp: "^#Color"
    replace: "Color"
