---

# Development configuration
- name: Installing common development tools
  pacman:
    state: latest
    name:
      - clang
      - cmake
      - gdb
      - git
      - sqlite

- name: Configuring .gitconfig
  template: src=gitconfig.j2 dest="/home/{{username}}/.gitconfig" owner={{username}} group={{username}} mode=0644

# Supported Languages
- ansible.builtin.include_tasks: go.yml
- ansible.builtin.include_tasks: java.yml
- ansible.builtin.include_tasks: javascript.yml
- ansible.builtin.include_tasks: python.yml
- ansible.builtin.include_tasks: ruby.yml
