---

# Python

- name: Installing Python
  pacman:
    state: latest
    name:
      - python
      - python-pip

- name: Installing 'pyenv'
  aur:
    name: pyenv
  become: yes
  become_user: aur_builder

- name: Installing Python tools
  pip:
    state: latest
    extra_args: --user
    name:
      - ipython
      - pip-tools
      - virtualenvwrapper
  become: yes
  become_user: "{{ username }}"
