---

# Python

- name: Installing Python
  community.general.pacman:
    state: latest
    name:
      - python
      - python-pip
      - python-setuptools

- name: Installing 'pyenv'
  kewlfft.aur.aur:
    use: yay
    name: pyenv
  become: yes
  become_user: aur_builder

- name: Installing Python tools
  pip:
    state: latest
    extra_args: --user
    name:
      - ipython
      - pip-tools
      - virtualenvwrapper
  become: yes
  become_user: "{{ username }}"
